<div class="row">
    <div class="col-md-12">
        <h3>
            <?php echo $this->getPageTitle(); ?>
        </h3>
        <hr class="hr-primary"/>
    </div>
</div>

<div class="row">

    <div class="col-md-2">

        <a href="<?php echo MY_HOST; ?>/config" class="btn btn-block btn-outline-primary btn-sm">Configurar ONU </a>


        <a href="<?php echo MY_HOST; ?>/change" class="btn btn-block btn-outline-primary btn-sm">Troca de ONU</a>


        <a href="<?php echo MY_HOST; ?>/reset" class="btn btn-block btn-outline-primary btn-sm">
            Rebootar ONU
        </a>

        <a href="<?php echo MY_HOST; ?>/mac" class="btn btn-block btn-outline-primary btn-sm">
            Enxergar MACs
        </a>

        <a href="<?php echo MY_HOST; ?>/activate" class="btn btn-block btn-outline-primary btn-sm">
            Ativar/Desativar porta
        </a>

        <a href="<?php echo MY_HOST; ?>/manager" class="btn btn-block btn-outline-primary btn-sm">
            GERENCIAR ONU BD
        </a>
    </div>
    <div class="col-md-4">

    </div>
    <div class="col-md-4">

    </div>

</div>