<div class="row">
    <div class="col-md-12">
        <h3 class="text-muted">
            <?php echo $this->getPageTitle(); ?>
        </h3>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <a href="/dtc/config">
            <button type="button" class="btn btn-primary btn-sm btnOnu">
                Configurar ONU
            </button>
        </a>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <a href="/dtc/change">
        <button type="button" class="btn btn-primary btn-sm btnOnu">
            Trocar ONU
        </button>
        </a>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <button type="button" class="btn btn-primary btn-sm btnOnu">
            Resetar ONU
        </button>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <button type="button" class="btn btn-primary btn-sm btnOnu">
            Ver macs na ONU
        </button>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>