<div class="row">
    <div class="col-md-4">
        <p></p>
        <h3>
            <?php echo $this->getPageTitle(); ?>
        </h3>
        <hr class="hr-primary"/>
        <div class="row">
            <div class="col-md-12">
                <a href="/dtc/config">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        Configurar ONU
                    </button>
                </a>
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-md-12">
                <a href="/dtc/change">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        Troca de ONU
                    </button>
                </a>
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-md-12">
                <a href="/dtc/reset">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        Rebootar ONU
                    </button>
                </a>
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-md-12">
                <a href="/dtc/mac">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        Enxergar MACs
                    </button>
                </a>
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-md-12">
                <a href="/dtc/activate">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        Ativar/Desativar porta
                    </button>
                </a>
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-md-12">
                <a href="/dtc/manager">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        GERENCIAR ONU BD
                    </button>
                </a>
            </div>
        </div>
        <p></p>
    </div>
</div>