<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->getPageTitle("-"); ?> Pnex-DTC</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="<?php echo MY_HOST; ?>/assets/css/bootstrap.min.css">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet" href=""<?php echo MY_HOST; ?>/assets/css/style.css">
    <!--    <link rel="stylesheet" href="/assets/css/menu.css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <link href="<?php echo MY_HOST; ?>/assets/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>

</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top ">
    <a class="navbar-brand" href="<?php echo MY_HOST; ?>/main">Pnex DTC</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                    <a class="dropdown-item" href="<?php echo MY_HOST; ?>/config">Configurar ONU</a>
                    <a class="dropdown-item" href="<?php echo MY_HOST; ?>/change">Trocar ONU</a>
                     <a class="dropdown-item" href="<?php echo MY_HOST; ?>/reset">Resetar ONU</a>
                     <a class="dropdown-item" href="<?php echo MY_HOST; ?>/mac">Verificar mac na ONU</a>
                     <a class="dropdown-item" href="<?php echo MY_HOST; ?>/activate">Ativat/Desativar porta</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="<?php echo MY_HOST; ?>/manager">Gerenciar bd ONU</a>
                </div>
            </li>

        </ul>

        <ul class="navbar-nav navbar-right">
            <?php if ($this->auth->check()): ?>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <img src="<?php echo MY_HOST; ?>/assets/open-iconic-master/svg/person.svg"
                             alt="account-logout"/> <?php echo $this->auth->name(); ?>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="<?php echo MY_HOST; ?>/logout"><img
                                    src="<?php echo MY_HOST; ?>/assets/open-iconic-master/svg/account-logout.svg"
                                    alt="account-logout"/> Logout</a>
                    </div>

                </li>
            <?php else: ?>
                <li><a href="<?php echo MY_HOST; ?>/login"><i class="glyphicon glyphicon-log-in"></i> Login</a></li>
                <li><a href="<?php echo MY_HOST; ?>/user/create"><i class="glyphicon glyphicon-pencil"></i> Register</a></li>
            <?php endif; ?>
        </ul>
    </div><!--/.navbar-collapse -->
    </div>
    </div>
</nav>

<main class="container">
