</main> <!-- /container -->

<hr>
<footer class="container">
    <p>&copy;2017 - Predialnet Provedor de Internet</p>
</footer>

<script src="<?php echo MY_HOST; ?>/assets/js/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<?php echo MY_HOST; ?>/assets/js/jquery.min.js"><\/script>')</script>

<script src="<?php echo MY_HOST; ?>/assets/js/bootstrap.min.js"></script>

<script src="<?php echo MY_HOST; ?>/assets/js/scripts.js"></script>
</body>
</html>
