<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->getPageTitle("-"); ?> Predialnet Predialfone</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <link rel="stylesheet" href="/assets/css/style.css">
<!--    <link rel="stylesheet" href="/assets/css/menu.css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <link href="/assets/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />

</head>

<?php
//session_start();
/*if ( !( isset($_SESSION['pnetuname'] ) ) || ( $_SESSION['pnetuname'] != $_SESSION[md5('seg'.$_SESSION['pnetuname'].$_SERVER['REMOTE_ADDR'].$_SERVER['HTTP_USER_AGENT'])] ) )
    header("location: /");*/

?>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">PREDIALNET</a>
        </div>


        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Menu <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php "BASEURL" ?>roteadores">Gerenciar Roteadores</a></li>

                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php  if ($this->auth->check()): ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="glyphicon glyphicon-user"></i> <?php echo $this->auth->name(); ?> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/logout"> <i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
                        </ul>
                    </li>
                <?php else: ?>
                    <li><a href="/login"><i class="glyphicon glyphicon-log-in"></i> Login</a></li>
                   <li><a href="/user/create"><i class="glyphicon glyphicon-pencil"></i> Register</a></li>
                <?php endif; ?>
            </ul>
        </div><!--/.navbar-collapse -->
    </div>
</nav>

<main class="container">
