<div class="bdy">
     <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
            <div id="pn-create">
                <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->getPageTitle() ?></h3>

                </div>
                <div class="panel-body">

                    <form action="<?php echo MY_HOST; ?>/user/store" method="post" accept-charset="utf-8">

                        <div class="form-group <?php echo (isset($this->error['name'])) ? 'has-error' : '' ?>">
                            <label for="name" class="control-label">Name</label>
                            <input type="text" name="name"  class="form-control"
                                   value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : '' ?>">
                            <?php if (isset($this->error['name'])): ?>
                                <span class="help-block"><?php echo $this->error['name'] ?></span>
                            <?php endif; ?>
                        </div>

                        <div class="form-group <?php echo (isset($this->error['email'])) ? 'has-error' : '' ?>">
                            <label for="email" class="control-label">E-mail</label>
                            <input type="text" name="email" class="form-control"
                                   value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : '' ?>">
                            <?php if (isset($this->error['email'])): ?>
                                <span class="help-block"><?php echo $this->error['email'] ?></span>
                            <?php endif; ?>
                        </div>

                        <div class="form-group <?php echo (isset($this->error['password'])) ? 'has-error' : '' ?>">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" name="password" class="form-control">
                            <?php if (isset($this->error['password'])): ?>
                                <span class="help-block"><?php echo $this->error['password'] ?></span>
                            <?php endif; ?>
                        </div>

                        <div class="form-group <?php echo (isset($this->error['user'])) ? 'has-error' : '' ?>">
                            <label for="name" class="control-label">User</label>
                            <input type="text" name="user"  class="form-control"
                                   value="<?php echo (isset($this->inputs['user'])) ? $this->inputs['user'] : '' ?>">
                            <?php if (isset($this->error['user'])): ?>
                                <span class="help-block"><?php echo $this->error['user'] ?></span>
                            <?php endif; ?>
                        </div>


                        <button type="submit" class="btn btn-primary">
                            <i class="glyphicon glyphicon-floppy-save" aria-hidden="true"></i> Save
                        </button>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>