<div class="row">
    <div class="col-md-12">
        <h1 class="h1" xmlns="http://www.w3.org/1999/html">Configurar ONU</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form role="form" method="post" name="onuForm" id="onuForm">
            <div class="form-group">

                <label for="chassi">
                    Chassi
                </label>
                <select name="chassi[]" id="chassi" class="form-control form-group-sm">
                    <option value="0">Chassi / Local</option>
                    <?php foreach ($this->view->chassi as $ch): ?>
                        <option value="<?php
                        $array = [$ch->id, $ch->actives_olt];
                        echo json_encode($array);
                        ?>">
                            <?php echo $ch->name; ?></option>

                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">

                <label for="olt">
                    OLT
                </label>
                <select name="olt" id="olt" class="form-control form-group-sm">
                    <option>Selecione um chassi</option>
                </select>
            </div>

            <div class="form-group">

                <label for="name">
                    Nome do local
                </label>
                <input type="text" required="required" name="name" class="form-control" id="name"/>

            </div>
            <div class="form-group">
                <label for="serial">
                    Serial number
                </label>
                <input type="text" name="serial" class="form-control" id="serial" required/>
            </div>
            <div class="form-group">
                <label for="service_port">
                    Service port novo
                </label>
                <input type="text" required name="service_port" class="form-control" id="service_port"
                       value="<?php echo (isset($this->view->servicePort)) ? $this->view->servicePort : ''; ?>"
                />
            </div>
            <div class="form-group">
                <label for="vlan">
                    Vlan nova
                </label>
                <input type="text" required name="vlan" class="form-control" id="vlan"
                       value="<?php echo (isset($this->view->vlan)) ? $this->view->vlan : ''; ?>"/>
                <input type="hidden" value="<?php print (isset($this->view->onuIndex)) ? $this->view->onuIndex : ''; ?>"
                       name="onu_index"/>
            </div>
            <button type="button" class="btn btn-default configOnu">
                Configurar
            </button>
            <button type="button" class="btn btn-default findMac">
                Buscar Serial
            </button>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <label for="tecnologia">
                        Tecnologia - Porta 1
                    </label>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="UTP"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control radioValue" aria-label="Text input with radio button"
                               placeholder="UTP">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="HPNA"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control" aria-label="Text input with radio button"
                               placeholder="HPNA">
                    </div>
                </div>
            </div>
        </div><!--fim do form group-->
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <label for="tecnologia">
                        Tecnologia - Porta 2
                    </label>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="UTP"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control radioValue" aria-label="Text input with radio button"
                               placeholder="UTP">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="HPNA"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control" aria-label="Text input with radio button"
                               placeholder="HPNA">
                    </div>
                </div>
            </div>
        </div><!--fim do form group-->
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <label for="tecnologia">
                        Tecnologia - Porta 3
                    </label>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="UTP"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control radioValue" aria-label="Text input with radio button"
                               placeholder="UTP">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="HPNA"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control" aria-label="Text input with radio button"
                               placeholder="HPNA">
                    </div>
                </div>
            </div>
        </div><!--fim do form group-->
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <label for="tecnologia">
                        Tecnologia - Porta 4
                    </label>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="UTP"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control radioValue" aria-label="Text input with radio button"
                               placeholder="UTP">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="porta[]" value="HPNA"
                                       aria-label="Checkbox for following text input">
                            </div>
                        </div>
                        <input type="text" class="form-control" aria-label="Text input with radio button"
                               placeholder="HPNA">
                    </div>
                </div>
            </div>
        </div><!--fim do form group-->
    </div>

    <div class="col-md-4">

    </div>
    </form>

</div>
<p></p>
<div class="row">
    <div class="col-md-6">
        <?php if (isset($this->view->mac)): ?>
            <div class="alert alert-<?php echo $this->view->class; ?>" role="alert" id="serialNumber">
                <?php if ($this->view->mac == "Nenhum gpon encontrado!"): ?>
                    <?php echo $this->view->mac; ?>
                <?php else: ?>
                    <button type="button" id="serialButton" class="btn btn-info">
                        <?php echo $this->view->mac; ?>
                    </button>
                    <span hidden id="chassiNumber">
                        <?php print "{$this->view->chassiNumber[0]}"; ?>
                    </span>

                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
    <?php //var_dump($this->view->chassiNumber);
    //var_dump($this->view->oltNumber);
    ?>
</div>

