<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <h2>
                EM CONSTRUÇÃO  <img src="<?php echo MY_HOST; ?>/assets/open-iconic-master/svg/wrench.svg" style="width: 25px;height: 25px;">
            </h2>
            <p>
                ainda to fazendo cavalo!
            </p>
            <p>
                <a class="btn btn-primary btn-large" href="/pnexdtc/main">Voltar</a>
            </p>
        </div>
    </div>
</div>